# Form implementation generated from reading ui file 'd:\1drive\OneDrive - Flexiv Ltd\桌面\code\QTRecord\src\input.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Input(object):
    def setupUi(self, Input, base_path):
        Input.setObjectName("Input")
        Input.resize(862, 717)
        icon = QtGui.QIcon()

        icon.addPixmap(QtGui.QPixmap(os.path.join(base_path, './asset/Icon/icon-robot.png')),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon.addPixmap(QtGui.QPixmap("./asset/Icon/icon-robot.png"),
        #                QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Input.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Input)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=Input)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(parent=Input)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./asset/Icon/icons-done.png"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(
            self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)

        self.retranslateUi(Input)
        QtCore.QMetaObject.connectSlotsByName(Input)

    def retranslateUi(self, Input):
        _translate = QtCore.QCoreApplication.translate
        Input.setWindowTitle(_translate("Input", "Input"))
        self.pushButton.setText(_translate("Input", "Done"))
