# Form implementation generated from reading ui file 'c:\Users\ke.li\iCloudDrive\Documents\RecordApp\src\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(798, 611)
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        self.frame_3.setGeometry(QtCore.QRect(60, 90, 501, 401))
        self.frame_3.setMinimumSize(QtCore.QSize(501, 401))
        self.frame_3.setMaximumSize(QtCore.QSize(501, 401))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 270, 340))
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.017, y1:0.630682, x2:1, y2:1, stop:0 rgba(117, 224, 213, 255), stop:1 rgba(240, 240, 240, 255));\n"
                                   "border-top-left-radius:20px;\n"
                                   "border-bottom-left-radius:20px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(250, 0, 245, 340))
        self.frame_2.setStyleSheet("background-color: rgb(240, 240, 240);\n"
                                   "\n"
                                   "border-top-right-radius:20px;\n"
                                   "border-bottom-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.close = QtWidgets.QPushButton(parent=self.frame_2)
        self.close.setGeometry(QtCore.QRect(220, 10, 16, 16))
        self.close.setMinimumSize(QtCore.QSize(16, 16))
        self.close.setMaximumSize(QtCore.QSize(16, 16))
        self.close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./asset/Icon/icons-close.png"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close.setIcon(icon)
        self.close.setObjectName("close")
        self.usr = QtWidgets.QLineEdit(parent=self.frame_2)
        self.usr.setGeometry(QtCore.QRect(100, 120, 120, 20))
        self.usr.setStyleSheet("border:1px solid;\n"
                               "background-color: rgb(255, 255, 255);\n"
                               "border-radius:5px;")
        self.usr.setObjectName("usr")
        self.pw = QtWidgets.QLineEdit(parent=self.frame_2)
        self.pw.setGeometry(QtCore.QRect(100, 200, 120, 20))
        self.pw.setStyleSheet("border:1px solid;\n"
                              "background-color: rgb(255, 255, 255);\n"
                              "border-radius:5px;")
        self.pw.setObjectName("pw")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 120, 65, 15))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 200, 65, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Login = QtWidgets.QPushButton(parent=self.frame_2)
        self.Login.setGeometry(QtCore.QRect(160, 290, 70, 22))
        self.Login.setStyleSheet("QPushButton {\n"
                                 "    background-color: rgb(216, 216, 216);\n"
                                 "  color: #fff;\n"
                                 "  border: none;\n"
                                 "  border-radius: 5px;\n"
                                 "  font-size: 12px;\n"
                                 "\n"
                                 "  text-align: center; /* 文本居中 */\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "  background-color: rgb(124, 222, 212);\n"
                                 "}\n"
                                 "\n"
                                 "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./asset/Icon/icons-send.png"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Login.setIcon(icon1)
        self.Login.setObjectName("Login")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(0, 210, 141, 151))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(
            "./asset/Icon/face_baby.png"))
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.close.raise_()
        self.usr.raise_()
        self.pw.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Login.raise_()
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(60, 180, 131, 190))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(
            "./asset/Icon/body_heart_01 (1).png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(110, 110, 131, 131))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(
            "./asset/Icon/body_heart_01.png"))
        self.label_6.setObjectName("label_6")
        self.label_4.raise_()
        self.label_5.raise_()
        self.frame_2.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Username:"))
        self.label_2.setText(_translate("Form", "Password:"))
        self.label_3.setText(_translate("Form", "Login"))
        self.Login.setText(_translate("Form", "Login"))
