# Form implementation generated from reading ui file 'c:\Users\Liaco\iCloudDrive\Desktop\QTRecord1 2\src\main1.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AutoRecord(object):
    def setupUi(self, AutoRecord, size, base_path):
        self.size = size
        self.base_path = base_path
        AutoRecord.setObjectName("AutoRecord")
        AutoRecord.resize(971, 797)
        AutoRecord.setMinimumSize(QtCore.QSize(480, 260))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icon-robot.png")),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AutoRecord.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=AutoRecord)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(8, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(
            self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.scroll_bar_style = """
            QScrollBar:vertical {
                border: none;
                background: #f0f0f0;
                width: 5px;
                margin: 0px 0px 0px 0px;
            }
            QScrollBar::handle:vertical {
                background: #888;
                min-height: 20px;
            }
            QScrollBar::add-line:vertical {
                height: 0px;
                subcontrol-position: bottom;
                subcontrol-origin: margin;
            }
            QScrollBar::sub-line:vertical {
                height: 0px;
                subcontrol-position: top;
                subcontrol-origin: margin;
            }
        """
        self.listWidget.setStyleSheet("ListView,\n"
                                      "ListWidget {\n"
                                      "    background: transparent;\n"
                                      "    outline: none;\n"
                                      "    border: none;\n"
                                      "    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
                                      "    selection-background-color: transparent;\n"
                                      "    alternate-background-color: transparent;\n"
                                      "}\n"
                                      "\n"
                                      "ListView::item,\n"
                                      "ListWidget::item {\n"
                                      "    background: transparent;\n"
                                      "    border: none;\n"
                                      "    padding-left: 11px;\n"
                                      "    padding-right: 11px;\n"
                                      "    height: 46px;\n"
                                      "}\n"
                                      "\n"
                                      "\n"
                                      "ListView::indicator,\n"
                                      "ListWidget::indicator {\n"
                                      "    width: 14px;\n"
                                      "    height: 14px;\n"
                                      "    border-radius: 3px;\n"
                                      "    border: 2px solid #49454F;\n"
                                      "    background-color: transparent;\n"
                                      "    margin-right: 8px;\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:hover,\n"
                                      "ListWidget::indicator:hover {\n"
                                      "    border: 2px solid #1D1B20;\n"
                                      "    background-color: rgba(0, 0, 0, 0.05);\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:pressed,\n"
                                      "ListWidget::indicator:pressed {\n"
                                      "    border: 2px solid #1D1B20;\n"
                                      "    background-color: rgba(0, 0, 0, 0.12);\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:checke,\n"
                                      "ListWidget::indicator:checked,\n"
                                      "ListView::indicator:indeterminate,\n"
                                      "ListWidget::indicator:indeterminate {\n"
                                      "    border: 1px solid #6750a4;\n"
                                      "    background-color: #6750a4;\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:checked,\n"
                                      "ListWidget::indicator:checked {\n"
                                      "    image: url(:/qmaterialwidgets/images/check_box/Accept_white.svg);\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:indeterminate,\n"
                                      "ListWidget::indicator:indeterminate {\n"
                                      "    image: url(:/qmaterialwidgets/images/check_box/PartialAccept_white.svg);\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:checked:hove,\n"
                                      "ListWidget::indicator:checked:hover,\n"
                                      "ListView::indicator:indeterminate:hover,\n"
                                      "ListWidget::indicator:indeterminate:hover {\n"
                                      "    border: 1px solid #6c54ac;\n"
                                      "    background-color: #6c54ac;\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:checked:presse,\n"
                                      "ListWidget::indicator:checked:pressed,\n"
                                      "ListView::indicator:indeterminate:pressed,\n"
                                      "ListWidget::indicator:indeterminate:pressed {\n"
                                      "    border: 1px solid #8373ac;\n"
                                      "    background-color: #8373ac;\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:disabled,\n"
                                      "ListWidget::indicator:disabled {\n"
                                      "    border: 2px solid rgb(199, 199, 199);\n"
                                      "    background-color: transparent;\n"
                                      "}\n"
                                      "\n"
                                      "ListView::indicator:checked:disable,\n"
                                      "ListWidget::indicator:checked:disabled,\n"
                                      "ListView::indicator:indeterminate:disabled,\n"
                                      "ListWidget::indicator:indeterminate:disabled {\n"
                                      "    border: 1px solid rgb(199, 199, 199);\n"
                                      "    background-color: rgb(199, 199, 199);\n"
                                      "}")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.verticalScrollBar().setStyleSheet(self.scroll_bar_style)
        self.splitter = QtWidgets.QSplitter(QtCore.Qt.Orientation.Vertical)

        # self.verticalLayout.addWidget(self.listWidget)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Import = QtWidgets.QPushButton(parent=self.frame_2)
        self.Import.setMinimumSize(QtCore.QSize(24, 24))
        self.Import.setMaximumSize(QtCore.QSize(24, 24))
        self.Import.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-import.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Import.setIcon(icon1)
        self.Import.setObjectName("Import")
        self.gridLayout.addWidget(
            self.Import, 0, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.Done = QtWidgets.QPushButton(parent=self.frame_2)
        self.Done.setMinimumSize(QtCore.QSize(24, 24))
        self.Done.setMaximumSize(QtCore.QSize(24, 24))
        self.Done.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-done.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Done.setIcon(icon2)
        self.Done.setObjectName("Done")
        self.gridLayout.addWidget(self.Done, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setStyleSheet("    outline: none;\n"
                                    "    border: none;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.verticalScrollBar().setStyleSheet(self.scroll_bar_style)
        self.verticalLayout_3.addWidget(self.textEdit)
        self.frame = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("#frame{background-color: rgb(255, 255, 255);\n"
                                 "border:none;}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 15, 12)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Send = QtWidgets.QPushButton(parent=self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-send.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Send.setIcon(icon3)
        self.Send.setObjectName("Send")
        self.verticalLayout_2.addWidget(
            self.Send, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_3.addWidget(self.frame)
        self.splitter.addWidget(self.listWidget)
        self.splitter.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.splitter)
        self.splitter.setSizes(self.size)
        AutoRecord.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AutoRecord)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSetting = QtWidgets.QMenu(parent=self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        AutoRecord.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AutoRecord)
        self.statusbar.setObjectName("statusbar")
        AutoRecord.setStatusBar(self.statusbar)
        self.actionnew = QtGui.QAction(parent=AutoRecord)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icon-new.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionnew.setIcon(icon4)
        self.actionnew.setObjectName("actionnew")
        self.actionOpen = QtGui.QAction(parent=AutoRecord)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-open.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtGui.QAction(parent=AutoRecord)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-close.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClose.setIcon(icon6)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtGui.QAction(parent=AutoRecord)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-save.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSave.setIcon(icon7)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtGui.QAction(parent=AutoRecord)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-undo.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionUndo.setIcon(icon8)
        self.actionUndo.setObjectName("actionUndo")
        self.actionAbout = QtGui.QAction(parent=AutoRecord)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-about.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAbout.setIcon(icon9)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCheck = QtGui.QAction(parent=AutoRecord)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-check.png")),
                         QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCheck.setIcon(icon10)
        self.actionCheck.setObjectName("actionCheck")
        self.actionSmall = QtGui.QAction(parent=AutoRecord)
        self.actionSmall.setObjectName("actionSmall")
        self.actionMedium = QtGui.QAction(parent=AutoRecord)
        self.actionMedium.setObjectName("actionMedium")
        self.actionLarge = QtGui.QAction(parent=AutoRecord)
        self.actionLarge.setObjectName("actionLarge")
        self.actionPrefrences = QtGui.QAction(parent=AutoRecord)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(os.path.join(self.base_path, "./asset/Icon/icons-setting.png")),
                         QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPrefrences.setIcon(icon11)
        self.actionPrefrences.setObjectName("actionPrefrences")
        self.menuFile.addAction(self.actionnew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionCheck)
        self.menuSetting.addAction(self.actionPrefrences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AutoRecord)
        QtCore.QMetaObject.connectSlotsByName(AutoRecord)

    def retranslateUi(self, AutoRecord):
        _translate = QtCore.QCoreApplication.translate
        AutoRecord.setWindowTitle(_translate("AutoRecord", "AutoRecord"))
        self.Send.setText(_translate("AutoRecord", "Send"))
        self.menuFile.setTitle(_translate("AutoRecord", "File"))
        self.menuEdit.setTitle(_translate("AutoRecord", "Edit"))
        self.menuSetting.setTitle(_translate("AutoRecord", "Setting"))
        self.menuHelp.setTitle(_translate("AutoRecord", "Help"))
        self.actionnew.setText(_translate("AutoRecord", "New"))
        self.actionOpen.setText(_translate("AutoRecord", "Open"))
        self.actionClose.setText(_translate("AutoRecord", "Close"))
        self.actionSave.setText(_translate("AutoRecord", "Save"))
        self.actionUndo.setText(_translate("AutoRecord", "Undo"))
        self.actionAbout.setText(_translate("AutoRecord", "About"))
        self.actionCheck.setText(_translate("AutoRecord", "Check"))
        self.actionSmall.setText(_translate("AutoRecord", "Small"))
        self.actionMedium.setText(_translate("AutoRecord", "Medium"))
        self.actionLarge.setText(_translate("AutoRecord", "Large"))
        self.actionPrefrences.setText(_translate("AutoRecord", "Prefrences"))
